# Generated by Django 5.1.7 on 2025-03-27 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_a_pagar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(max_length=50)),
                ('total_gasto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_propina', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('modo_propina', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='task',
            old_name='tittle',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='task',
            name='datecompleted',
        ),
        migrations.AddField(
            model_name='task',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DetalleGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribucion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.gasto')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks.participante')),
            ],
        ),
        migrations.CreateModel(
            name='Propina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_propina', models.DecimalField(decimal_places=2, max_digits=10)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks.participante')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.sesion', unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='participante',
            name='sesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.sesion'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='sesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.sesion'),
        ),
        migrations.AddField(
            model_name='participante',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.usuario'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.usuario'),
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=50)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.usuario')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='participante',
            unique_together={('usuario', 'sesion')},
        ),
    ]
