# Generated by Django 5.1.7 on 2025-04-04 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_usuario_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='sesion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.sesion'),
        ),
    ]
