# Generated by Django 5.2.1 on 2025-05-14 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_gasto_sesion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propina',
            name='sesion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tasks.sesion'),
        ),
    ]
